configuration: Release

image: Visual Studio 2017
clone_depth: 1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
  - dotnet restore --verbosity quiet

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: NExFStFGj+2jJCF1eVEvSWR5K2Mu0U44oks2+7kaRFbXEfCPqM4FJoSgP+AF/Vau
  on:
    appveyor_repo_tag: true